this["JST"] = this["JST"] || {};

this["JST"]["TEMPLATES/RENDER_TOP.PUG"] = function pug_escape(e){var a=""+e,t=pug_match_html.exec(a);if(!t)return e;var r,c,n,s="";for(r=t.index,c=0;r<a.length;r++){switch(a.charCodeAt(r)){case 34:n="&quot;";break;case 38:n="&amp;";break;case 60:n="&lt;";break;case 62:n="&gt;";break;default:continue}c!==r&&(s+=a.substring(c,r)),c=r+1,s+=n}return c!==r?s+a.substring(c,r):s}
var pug_match_html=/["&<>]/;
function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {;var locals_for_with = (locals || {});(function (user, window) {;pug_debug_line = 1;pug_debug_filename = "templates\u002Frender_top.pug";
if (window.user) {
;pug_debug_line = 2;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "\u003Ca data-page=\"index\"\u003E";
;pug_debug_line = 2;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "В меню\u003C\u002Fa\u003E";
;pug_debug_line = 3;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "";
;pug_debug_line = 4;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "\u003Cspan class=\"divider-dot\"\u003E";
;pug_debug_line = 4;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "&#183;\u003C\u002Fspan\u003E";
;pug_debug_line = 5;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "";
;pug_debug_line = 6;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "\u003Ca data-page=\"leaders\"\u003E";
;pug_debug_line = 6;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "Привет, ";
;pug_debug_line = 6;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + (pug_escape(null == (pug_interp = user.name) ? "" : pug_interp));
;pug_debug_line = 6;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "!\u003C\u002Fa\u003E";
;pug_debug_line = 7;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "";
;pug_debug_line = 8;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "\u003Cspan class=\"divider-dot\"\u003E";
;pug_debug_line = 8;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "&#183;\u003C\u002Fspan\u003E";
;pug_debug_line = 9;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "";
;pug_debug_line = 10;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "\u003Ca data-page=\"logout\"\u003E";
;pug_debug_line = 10;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "Выйти\u003C\u002Fa\u003E";
}
else {
;pug_debug_line = 12;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "\u003Ca data-page=\"index\"\u003E";
;pug_debug_line = 12;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "Меню\u003C\u002Fa\u003E";
;pug_debug_line = 13;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "";
;pug_debug_line = 14;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "\u003Cspan class=\"divider-dot\"\u003E";
;pug_debug_line = 14;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "&#183;\u003C\u002Fspan\u003E";
;pug_debug_line = 15;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "";
;pug_debug_line = 16;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "\u003Ca data-page=\"login\"\u003E";
;pug_debug_line = 16;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "Войти\u003C\u002Fa\u003E";
;pug_debug_line = 17;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "";
;pug_debug_line = 18;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "\u003Cspan class=\"divider-dot\"\u003E";
;pug_debug_line = 18;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "&#183;\u003C\u002Fspan\u003E";
;pug_debug_line = 19;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "";
;pug_debug_line = 20;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "\u003Ca data-page=\"signup\"\u003E";
;pug_debug_line = 20;pug_debug_filename = "templates\u002Frender_top.pug";
pug_html = pug_html + "Зарегистрироваться\u003C\u002Fa\u003E";
}}.call(this,"user" in locals_for_with?locals_for_with.user:typeof user!=="undefined"?user:undefined,"window" in locals_for_with?locals_for_with.window:typeof window!=="undefined"?window:undefined));} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line);};return pug_html;};