this["JST"] = this["JST"] || {};

this["JST"]["TEMPLATES/RENDER_LOGIN.PUG"] = function pug_rethrow(n,e,r,t){if(!(n instanceof Error))throw n;if(!("undefined"==typeof window&&e||t))throw n.message+=" on line "+r,n;try{t=t||require("fs").readFileSync(e,"utf8")}catch(e){pug_rethrow(n,null,r)}var i=3,a=t.split("\n"),o=Math.max(r-i,0),h=Math.min(a.length,r+i),i=a.slice(o,h).map(function(n,e){var t=e+o+1;return(t==r?"  > ":"    ")+t+"| "+n}).join("\n");throw n.path=e,n.message=(e||"Pug")+":"+r+"\n"+i+"\n\n"+n.message,n}function template(locals) {var pug_html = "", pug_mixins = {}, pug_interp;var pug_debug_filename, pug_debug_line;try {;pug_debug_line = 1;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "\u003Cform class=\"login\" autocomplete=\"off\"\u003E";
;pug_debug_line = 2;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 3;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "\u003Clabel for=\"username\"\u003E";
;pug_debug_line = 3;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "Логин:\u003C\u002Flabel\u003E";
;pug_debug_line = 4;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "\u003Cinput type=\"text\" id=\"username\" autofocus=\"autofocus\" placeholder=\"Введите логин\"\u002F\u003E";
;pug_debug_line = 5;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "\u003Clabel class=\"error\" for=\"username\"\u003E\u003C\u002Flabel\u003E\u003C\u002Fp\u003E";
;pug_debug_line = 6;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 7;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "\u003Clabel for=\"password\"\u003E";
;pug_debug_line = 7;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "Пароль:\u003C\u002Flabel\u003E";
;pug_debug_line = 8;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "\u003Cinput type=\"password\" id=\"password\" placeholder=\"Введите пароль\"\u002F\u003E";
;pug_debug_line = 9;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "\u003Clabel class=\"error\" for=\"password\"\u003E\u003C\u002Flabel\u003E\u003C\u002Fp\u003E";
;pug_debug_line = 10;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "\u003Cp\u003E";
;pug_debug_line = 11;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "\u003Cinput class=\"submit\" type=\"submit\" value=\"Войти\"\u002F\u003E\u003C\u002Fp\u003E";
;pug_debug_line = 12;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "\u003Ca data-page=\"signup\"\u003E";
;pug_debug_line = 12;pug_debug_filename = "templates\u002Frender_login.pug";
pug_html = pug_html + "Зарегистрироваться\u003C\u002Fa\u003E\u003C\u002Fform\u003E";} catch (err) {pug_rethrow(err, pug_debug_filename, pug_debug_line);};return pug_html;};